# Generated by Django 2.0 on 2022-05-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Price', models.IntegerField(null=True)),
                ('Registered_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=120, null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('Geo_Location', models.CharField(max_length=120, null=True)),
                ('Registered_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=120, null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('Geo_Location', models.CharField(max_length=120, null=True)),
                ('Registered_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Store_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Store_detail'),
        ),
    ]
