# Generated by Django 2.0 on 2022-05-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='Store_Name',
            new_name='Store',
        ),
    ]
