# Generated by Django 2.0 on 2022-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0002_auto_20220517_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='Product_Price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
