# Generated by Django 2.0 on 2022-05-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0003_auto_20220517_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Product_Description',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='Product_Price',
            field=models.IntegerField(null=True),
        ),
    ]
