# Generated by Django 2.0 on 2022-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0004_auto_20220518_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='Product_Description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
