# Generated by Django 2.0 on 2022-05-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0006_auto_20220518_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Cart_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Product_detail')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Store_detail')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.User_detail')),
            ],
        ),
    ]
