# Generated by Django 2.0 on 2022-05-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0007_user_cart_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Token', models.IntegerField(null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.User_detail')),
            ],
        ),
    ]
