# Generated by Django 2.0 on 2022-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0009_auto_20220519_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_security',
            name='Token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
