# Generated by Django 2.0 on 2022-05-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0011_auto_20220519_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(null=True)),
                ('Ordered_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Token', models.CharField(max_length=100, null=True)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Store_detail')),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Cart_detail',
            new_name='Cart_detail',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Cart_detail'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Product_detail'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.Store_detail'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inno_Extrabeing.User_detail'),
        ),
    ]
