# Generated by Django 2.0 on 2022-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0012_auto_20220519_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_detail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cart_detail',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='cart_detail',
            name='Store',
        ),
        migrations.AddField(
            model_name='cart_detail',
            name='Detail',
            field=models.TextField(null=True),
        ),
    ]
