# Generated by Django 2.0 on 2022-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0014_auto_20220519_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_security',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
