# Generated by Django 2.0 on 2022-05-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0015_auto_20220519_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='Price',
            new_name='Quantity',
        ),
        migrations.AddField(
            model_name='store_security',
            name='Generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_security',
            name='Generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Ordered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
