# Generated by Django 2.0 on 2022-05-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0016_auto_20220519_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='Order_Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='store_security',
            name='Token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_security',
            name='Token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
