# Generated by Django 2.0 on 2022-05-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0017_auto_20220520_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='Cart',
        ),
    ]
