# Generated by Django 2.0 on 2022-05-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0018_remove_order_detail_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='Order_Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
