# Generated by Django 2.0 on 2022-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inno_Extrabeing', '0019_auto_20220520_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Product_image',
            field=models.ImageField(default='', upload_to='Product/Images'),
        ),
    ]
